### PR TITLE
Enhancement for animals query for filters

### LINKED ISSUE #303: Enhancement for breeds query
**Goal**
Enhancement for breeds query

**Description**
- [ ] Make species parameter optional. If not specified, return all species breeds
- [ ] Add `speciesId` and `speciesValue` fields

**Expected behaviour**
Such GraphQL query

```gql
{
  breeds(language:"lt") {
    id
    value
    abbreviation
    speciesId
    speciesValue
  }
}
```

Should return all breeds entries for the species, e.g. (only sample):
```gql
{
  "data": {
      "breeds": [
          {
            "id": 12,
            "value": "Afenpinčeriai",
            "abbreviation": "AP",
            "speciesId": 1,
            "speciesValue": Šuo
          }
    ]
}
```

### LINKED ISSUE #305: Enhancement for animals query for filters
**Goal**
Improve the query to handle all filters

**Description**
It has been observed that certain filter fail on the `animals` GraphQL query. For example:

```gql
animals(first: 2, gender: 2, after: "Mg==") 
animals(first: 2, gender: 2, species: 1) 
animals(first: 2, gender: 2, breed: 205) 
```

Please fix all of them and add tests to ensure it

### PR DESCRIPTION
**Pull request by AzisK**
Fix the query and add tests for such cases

Closes #305

### CODE REVIEW

File: src/sql-queries/animal.ts [hunk 1]
```diff
@@ -93,29 +93,26 @@ export const getAnimalsQuery = (
         query.leftJoin('breed AS b').on('ad.breed_id', 'b.id')
         : query;
     query = ids ? query.where($in('a.id', ids)) : query;
-    query = species ? query.where($in('b.species', species)) : query;
-    query = gender ? query.where($in('ad.gender_id', gender)) : query;
-    query = breed ? query.where($in('ad.breed_id', breed)) : query;
+    query = species ? query.where($in('b.species', species.map(String))) : query;
+    query = gender ? query.where($in('ad.gender_id', gender.map(String))) : query;
+    query = breed ? query.where($in('ad.breed_id', breed.map(String))) : query;
```
Comment (pergaliuke) [inline src/sql-queries/animal.ts:98]: In my understanding, for breed we do not need mapping, because breed_id has integer type in animal_details.

**Review by pergaliuke — APPROVED** [review]

**Comment by pergaliuke** [comment]
The wrong issue has been tagged. It should be #305

File: src/sql-queries/animal.ts (hunk 1 above)
Comment (AzisK) [reply src/sql-queries/animal.ts:98]: Indeed. That is true. Thanks!
